export const GET_POSTS_BY_REQUEST = 'GET_POSTS_BY_REQUEST';
export const GET_POSTS_BY_SUCCESS = 'GET_POSTS_BY_SUCCESS';
export const GET_POSTS_BY_FAIL = 'GET_POSTS_BY_FAIL';
export const SEARCH_QUERY_REQUEST = 'SEARCH_QUERY_REQUEST';
export const SEARCH_QUERY_SUCCESS = 'SEARCH_QUERY_SUCCESS';
export const SEARCH_QUERY_FAIL = 'SEARCH_QUERY_FAIL';
export const SEARCH_QUERY_TEXT = 'SEARCH_QUERY_TEXT';
